#!/usr/bin/env python3
"""Shadow C2 — WAF Detection"""

import re
from server.utils.network import make_request


class WAFDetector:
    """Detect Web Application Firewalls via header/response analysis."""

    WAF_SIGNATURES = {
        "Cloudflare": {
            "headers": ["cf-ray", "cf-cache-status", "cf-request-id"],
            "cookies": ["__cfduid", "cf_clearance", "__cf_bm"],
            "body": ["Attention Required! | Cloudflare", "cloudflare-nginx",
                      "Cloudflare Ray ID"],
            "server": ["cloudflare"],
        },
        "Sucuri": {
            "headers": ["x-sucuri-id", "x-sucuri-cache"],
            "cookies": ["sucuri_"],
            "body": ["Access Denied - Sucuri", "Sucuri WebSite Firewall"],
            "server": ["Sucuri"],
        },
        "Imperva": {
            "headers": ["x-cdn", "x-iinfo"],
            "cookies": ["incap_ses_", "visid_incap_", "nlbi_"],
            "body": ["Incapsula incident", "_Incapsula_Resource"],
            "server": ["Incapsula"],
        },
        "Akamai": {
            "headers": ["x-akamai-transformed", "akamai-origin-hop"],
            "cookies": ["AKA_A2", "akamai"],
            "body": ["Access Denied.*akamai", "Reference.*akamai"],
            "server": ["AkamaiGHost"],
        },
        "AWS WAF": {
            "headers": ["x-amzn-requestid", "x-amz-cf-id"],
            "cookies": ["AWSALB", "AWSALBCORS"],
            "body": ["<TITLE>ERROR: The request could not be satisfied"],
            "server": ["awselb"],
        },
        "F5 BIG-IP": {
            "headers": ["x-wa-info"],
            "cookies": ["BIGipServer", "TS01"],
            "body": ["The requested URL was rejected"],
            "server": ["BigIP", "BIG-IP"],
        },
        "Barracuda": {
            "headers": ["barra_counter_session"],
            "cookies": ["barra_counter_session"],
            "body": ["Barracuda Web Application Firewall"],
            "server": ["Barracuda"],
        },
        "ModSecurity": {
            "headers": ["x-mod-security"],
            "cookies": [],
            "body": ["ModSecurity", "Mod_Security", "NOYB",
                      "This error was generated by Mod_Security"],
            "server": ["Mod_Security"],
        },
        "Wordfence": {
            "headers": [],
            "cookies": ["wfvt_", "wordfence"],
            "body": ["Generated by Wordfence", "wfAction=",
                      "wordfence-ls", "Your access to this site has been limited"],
            "server": [],
        },
        "Comodo": {
            "headers": [],
            "cookies": [],
            "body": ["Protected by COMODO", "WAF by Comodo"],
            "server": ["Comodo"],
        },
    }

    def detect(self, url: str) -> dict:
        """
        Detect WAF on target URL.
        Returns {detected, waf_name, confidence, details, all_detected}.
        """
        result = {
            "detected": False,
            "waf_name": "",
            "confidence": 0.0,
            "details": "",
            "all_detected": [],
        }

        # Normal request
        resp = make_request(url)
        headers = {k.lower(): v for k, v in resp.headers.items()}
        body = resp.text
        cookies = headers.get("set-cookie", "")
        server = headers.get("server", "")

        # Malicious request to trigger WAF block
        mal_url = url.rstrip("/") + "/?id=1%27%20OR%201=1--&<script>alert(1)</script>"
        mal_resp = make_request(mal_url)
        mal_headers = {k.lower(): v for k, v in mal_resp.headers.items()}
        mal_body = mal_resp.text

        detections = []

        for waf_name, sigs in self.WAF_SIGNATURES.items():
            score = 0.0
            reasons = []

            # Check headers
            for h in sigs.get("headers", []):
                if h.lower() in headers or h.lower() in mal_headers:
                    score += 0.3
                    reasons.append(f"Header: {h}")

            # Check cookies
            for c in sigs.get("cookies", []):
                if c.lower() in cookies.lower():
                    score += 0.2
                    reasons.append(f"Cookie: {c}")

            # Check server header
            for s in sigs.get("server", []):
                if s.lower() in server.lower():
                    score += 0.3
                    reasons.append(f"Server: {s}")

            # Check body patterns (both normal and blocked response)
            for pattern in sigs.get("body", []):
                if re.search(pattern, body, re.IGNORECASE):
                    score += 0.2
                    reasons.append(f"Body pattern: {pattern[:30]}")
                if re.search(pattern, mal_body, re.IGNORECASE):
                    score += 0.3
                    reasons.append(f"Block page pattern: {pattern[:30]}")

            # Check if malicious request was blocked (403, 406, 429, 503)
            if mal_resp.status_code in (403, 406, 429, 503) and score > 0:
                score += 0.2
                reasons.append(f"Blocked with HTTP {mal_resp.status_code}")

            if score > 0.2:
                detections.append({
                    "waf_name": waf_name,
                    "confidence": min(score, 1.0),
                    "reasons": reasons,
                })

        if detections:
            # Sort by confidence
            detections.sort(key=lambda x: x["confidence"], reverse=True)
            best = detections[0]
            result["detected"] = True
            result["waf_name"] = best["waf_name"]
            result["confidence"] = best["confidence"]
            result["details"] = ", ".join(best["reasons"])
            result["all_detected"] = detections

        return result
